### ISSUE TITLE
Enable security/taint analysis

### ISSUE THREAD

**Issue by muglug** [psalm/psalm-github-actions#19]
```
    - name: Psalm
       uses: docker://vimeo/psalm-github-actions
       with:
        security_analysis: true
        report_file: results.sarif
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
```

Or similar
