### ISSUE TITLE
Security Analysis Upload fails (report.sarif not found)

### ISSUE THREAD

**Issue by davidsneighbour** [psalm/psalm-github-actions#23]
workflow file:

```
name: Psalm Static Analysis

on: [push, pull_request]

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
        with:
          composer_require_dev: true
          #composer_ignore_platform_reqs: true
          security_analysis: true
          report_file: results.sarif

      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
```

Error in `Upload Security Analysis results to GitHub`:

```
Run github/codeql-action/upload-sarif@v1
Error: Path does not exist: results.sarif
Error: Path does not exist: results.sarif
    at Object.upload (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-lib.js:71:15)
    at run (/home/runner/work/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:29:46)
```

Security Analysis on the repo is enabled, but it seems like they might expect an empty report file or somehow the resulting report file is not saved where the scripts would expect it?

There are two open issues that sound like they are connected:

- https://github.com/github/codeql-action/issues/282
- https://github.com/github/codeql-action/issues/220

Maybe it's possible to add some form of empty minimal `results.sarif` on run?
